var word1 = 'hello';
var word2 = 'owu';
var word3 = 'com';
var word4 = 'ua';
var num1 = 1;
var num2 = 10;
var num3 = -999;
var num4 = 123;
var num5 = 3.14;
var num6 = 2.7;
var num7 = 16;
var bool1 = true;
var bool2 = false;
var firstName = 'Dmytro';
var middleName = 'Illich';
var lastName = 'Shaposhnikov';
var person = "".concat(lastName, " ").concat(firstName, " ").concat(middleName);
console.log(word1);
console.log(word2);
console.log(word3);
console.log(word4);
console.log(num1);
console.log(num2);
console.log(num3);
console.log(num4);
console.log(num5);
console.log(num6);
console.log(num7);
console.log(bool1);
console.log(bool2);
console.log(person);
var a = 100;
var b = '100';
var c = true;
console.log(typeof a);
console.log(typeof b);
console.log(typeof c);
var prompt1 = prompt('What is your firstname?');
var prompt2 = prompt('What is your middlename?');
var prompt3 = prompt('What is your age');
console.log("firstname: ".concat(prompt1));
console.log("middlename: ".concat(prompt2));
console.log("age: ".concat(prompt3));
